# 测试配置文件
# 
# 
server:
  port: 8101
spring:
  main:
      log-startup-info: true


  logging:
    level:
      org.springframework: DEBUG
      org.springframework.beans.factory: DEBUG
      org.springframework.context: DEBUG
  ai:
    openai:
      api-key: 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
    chat:
      options:
        model: gpt-4o-mini
        temperature: 0.7
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/techInterviewWeb
    username: root
    password: 123456
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456

  knife4j:
    enable: false
